version: '3.8'
services:
  backend:
    image: coffee-marketplace
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8181"
    depends_on:
      flyway:
        condition: service_completed_successfully
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/marketplace

  flyway:
    image: flyway/flyway
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./data/src/main/resources/flyway.config:/flyway/conf/flyway.config
      - ./data/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - service-db

  service-db:
    image: postgres:15
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./dist/database:/var/lib/postgresql/data/pgdata/
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./dist/pgadmin:/var/lib/pgadmin
    restart: always
